#!/usr/bin/env node
/**
 * Docs Build Script
 * Aggregates documentation, architecture, entities, and mockups into a docsify site.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const DOCS_DIR = path.join(ROOT, 'docs');

// Content directories to include
const CONTENT_DIRS = [
  { source: 'documentation', target: 'documentation', title: 'Documentation' },
  { source: 'architecture', target: 'architecture', title: 'Architecture' },
  { source: 'entities', target: 'entities', title: 'Entities' },
  { source: 'mockups', target: 'mockups', title: 'Mockups' }
];

// Ensure docs directory exists and is clean
function prepareBuildDir() {
  if (fs.existsSync(DOCS_DIR)) {
    fs.rmSync(DOCS_DIR, { recursive: true });
  }
  fs.mkdirSync(DOCS_DIR, { recursive: true });
  console.log('✓ Prepared docs directory');
}

// Copy README.md as the main index
function copyReadme() {
  const readmeSrc = path.join(ROOT, 'README.md');
  const readmeDst = path.join(DOCS_DIR, 'README.md');
  fs.copyFileSync(readmeSrc, readmeDst);
  console.log('✓ Copied README.md as homepage');
}

// Copy content directories
function copyContentDirs() {
  for (const dir of CONTENT_DIRS) {
    const srcPath = path.join(ROOT, dir.source);
    const dstPath = path.join(DOCS_DIR, dir.target);
    
    if (!fs.existsSync(srcPath)) {
      console.warn(`⚠ Source directory not found: ${dir.source}`);
      continue;
    }
    
    fs.mkdirSync(dstPath, { recursive: true });
    
    const files = fs.readdirSync(srcPath);
    for (const file of files) {
      if (file.endsWith('.md')) {
        fs.copyFileSync(
          path.join(srcPath, file),
          path.join(dstPath, file)
        );
      }
    }
    console.log(`✓ Copied ${dir.source}/ (${files.filter(f => f.endsWith('.md')).length} files)`);
  }
}

// Copy UI assets if present
function copyAssets() {
  const assetsSrc = path.join(ROOT, 'ui_assets');
  const assetsDst = path.join(DOCS_DIR, 'ui_assets');
  
  if (fs.existsSync(assetsSrc)) {
    fs.mkdirSync(assetsDst, { recursive: true });
    const files = fs.readdirSync(assetsSrc);
    for (const file of files) {
      const srcFile = path.join(assetsSrc, file);
      const dstFile = path.join(assetsDst, file);
      if (fs.statSync(srcFile).isFile()) {
        fs.copyFileSync(srcFile, dstFile);
      }
    }
    console.log(`✓ Copied ui_assets/ (${files.length} files)`);
  }
}

// Generate sidebar navigation
function generateSidebar() {
  let sidebar = '<!-- Generated by build-docs.js -->\n\n';
  sidebar += '* [Home](/)\n\n';
  
  for (const dir of CONTENT_DIRS) {
    const dirPath = path.join(DOCS_DIR, dir.target);
    if (!fs.existsSync(dirPath)) continue;
    
    sidebar += `* **${dir.title}**\n`;
    
    const files = fs.readdirSync(dirPath)
      .filter(f => f.endsWith('.md'))
      .sort();
    
    for (const file of files) {
      const name = file.replace('.md', '')
        .replace(/_/g, ' ')
        .replace(/\b\w/g, c => c.toUpperCase());
      sidebar += `  * [${name}](/${dir.target}/${file})\n`;
    }
    sidebar += '\n';
  }
  
  fs.writeFileSync(path.join(DOCS_DIR, '_sidebar.md'), sidebar);
  console.log('✓ Generated _sidebar.md');
}

// Generate navbar
function generateNavbar() {
  let navbar = '<!-- Generated by build-docs.js -->\n\n';
  navbar += '* [Home](/)\n';
  
  for (const dir of CONTENT_DIRS) {
    const dirPath = path.join(DOCS_DIR, dir.target);
    if (!fs.existsSync(dirPath)) continue;
    navbar += `* [${dir.title}](/${dir.target}/)\n`;
  }
  
  fs.writeFileSync(path.join(DOCS_DIR, '_navbar.md'), navbar);
  console.log('✓ Generated _navbar.md');
}

// Generate docsify index.html
function generateIndexHtml() {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Skin Zone - Multi-Tenant Beauty Marketplace Documentation">
  <title>Skin Zone Documentation</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsify@4/lib/themes/vue.css">
  <style>
    :root {
      --theme-color: #e91e63;
    }
    .sidebar-nav > ul > li > a {
      font-weight: bold;
    }
    /* Accessibility: ensure focus is visible */
    a:focus, button:focus {
      outline: 2px solid var(--theme-color);
      outline-offset: 2px;
    }
    /* Responsive adjustments */
    @media screen and (max-width: 768px) {
      .sidebar {
        width: 100%;
      }
    }
    /* Reduced motion preference */
    @media (prefers-reduced-motion: reduce) {
      * {
        transition: none !important;
        animation: none !important;
      }
    }
  </style>
</head>
<body>
  <div id="app">Loading documentation...</div>
  <script>
    window.$docsify = {
      name: 'Skin Zone',
      repo: '',
      loadSidebar: true,
      loadNavbar: true,
      subMaxLevel: 3,
      auto2top: true,
      search: {
        placeholder: 'Search documentation',
        noData: 'No results found',
        depth: 3
      },
      pagination: {
        previousText: 'Previous',
        nextText: 'Next',
        crossChapter: true
      }
    };
  </script>
  <script src="https://cdn.jsdelivr.net/npm/docsify@4/lib/docsify.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/docsify@4/lib/plugins/search.min.js"></script>
</body>
</html>`;
  
  fs.writeFileSync(path.join(DOCS_DIR, 'index.html'), html);
  console.log('✓ Generated index.html');
}

// Generate .nojekyll file for GitHub Pages
function generateNojekyll() {
  fs.writeFileSync(path.join(DOCS_DIR, '.nojekyll'), '');
  console.log('✓ Generated .nojekyll');
}

// Main build function
function build() {
  console.log('\n🔨 Building documentation site...\n');
  
  try {
    prepareBuildDir();
    copyReadme();
    copyContentDirs();
    copyAssets();
    generateSidebar();
    generateNavbar();
    generateIndexHtml();
    generateNojekyll();
    
    console.log('\n✅ Documentation build complete!\n');
    console.log(`   Output: ${DOCS_DIR}`);
    console.log('   Run "npm run docs:serve" to preview locally\n');
  } catch (error) {
    console.error('\n❌ Build failed:', error.message);
    process.exit(1);
  }
}

build();
